# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af40503afb9efb9b991a9ee8e39042b4"
name = "99-frames-price-calculator"
handle = "99-frames-price-calculator"
application_url = "https://patrick-researchers-factor-read.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shini-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://99-frames-price-calculator.fly.dev/auth/callback",
  "https://citations-records-contains-temperature.trycloudflare.com/auth/callback",
  "https://citations-records-contains-temperature.trycloudflare.com/auth/shopify/callback",
  "https://citations-records-contains-temperature.trycloudflare.com/api/auth/callback",
  "https://characterization-authentication-association-inherited.trycloudflare.com/auth/callback",
  "https://characterization-authentication-association-inherited.trycloudflare.com/auth/shopify/callback",
  "https://characterization-authentication-association-inherited.trycloudflare.com/api/auth/callback",
  "https://stakeholders-each-author-fabrics.trycloudflare.com/auth/callback",
  "https://stakeholders-each-author-fabrics.trycloudflare.com/auth/shopify/callback",
  "https://stakeholders-each-author-fabrics.trycloudflare.com/api/auth/callback",
  "https://suited-blair-latvia-athletics.trycloudflare.com/auth/callback",
  "https://suited-blair-latvia-athletics.trycloudflare.com/auth/shopify/callback",
  "https://suited-blair-latvia-athletics.trycloudflare.com/api/auth/callback",
  "https://messaging-thinking-julia-clone.trycloudflare.com/auth/callback",
  "https://messaging-thinking-julia-clone.trycloudflare.com/auth/shopify/callback",
  "https://messaging-thinking-julia-clone.trycloudflare.com/api/auth/callback",
  "https://granny-truck-nu-imaging.trycloudflare.com/auth/callback",
  "https://granny-truck-nu-imaging.trycloudflare.com/auth/shopify/callback",
  "https://granny-truck-nu-imaging.trycloudflare.com/api/auth/callback",
  "https://meet-existed-agenda-dirt.trycloudflare.com/auth/callback",
  "https://meet-existed-agenda-dirt.trycloudflare.com/auth/shopify/callback",
  "https://meet-existed-agenda-dirt.trycloudflare.com/api/auth/callback",
  "https://wool-springer-handled-cast.trycloudflare.com/auth/callback",
  "https://wool-springer-handled-cast.trycloudflare.com/auth/shopify/callback",
  "https://wool-springer-handled-cast.trycloudflare.com/api/auth/callback",
  "https://patrick-researchers-factor-read.trycloudflare.com/auth/callback",
  "https://patrick-researchers-factor-read.trycloudflare.com/auth/shopify/callback",
  "https://patrick-researchers-factor-read.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
